from matplotlib import pyplot as plt
from STRUC_Stiffness import *

x, y, z = axes(use_beam)
V_x, V_y = v_beam(use_beam, use_loadcase)
M_x, M_y = m_beam(use_beam, use_loadcase)
sigma_zx, sigma_zy = stress_beam(use_beam, use_loadcase)
shear_x, shear_y = shear_beam(use_beam, use_loadcase)

fig1, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
plt.gcf().subplots_adjust(left=0.15)
ax1.plot(z, V_x)
ax1.set_ylim(np.min(V_x)*1.1, 0)
ax1.set_title("Internal Load diagram xz-plane")
ax1.set(ylabel=r'$\bar{V}_x$ [N]')
ax1.grid(True)
ax1.axhline(0, color='black', lw=1.2)
ax2.plot(z, M_y)
ax2.set_title("Bending Moment diagram xz-plane")
ax2.set(xlabel=r'$z$ [m]', ylabel=r'$\bar{M}_y$ [N/m]')
ax2.grid(True)
ax2.axhline(0, color='black', lw=1.2)
fig1.savefig("Loading_diagrams_xz")

fig2, (ax3, ax4) = plt.subplots(2, 1, sharex=True)
plt.gcf().subplots_adjust(left=0.15)
ax3.plot(z, V_y)
ax3.set_ylim(np.min(V_y)*1.1, 0)
ax3.set_title("Internal Load diagram yz-plane")
ax3.set(ylabel=r'$\bar{V}_y$ [N]')
ax3.grid(True)
ax3.axhline(0, color='black', lw=1.2)
ax4.plot(z, M_x)
ax4.set_title("Bending Moment diagram yz-plane")
ax4.set(xlabel=r'$z$ [m]', ylabel=r'$\bar{M}_x$ [N/m]')
ax4.grid(True)
ax4.axhline(0, color='black', lw=1.2)
fig2.savefig("Loading_diagrams_yz")

fig3, (ax5, ax6) = plt.subplots(1, 2, sharey=True)
ax5.plot(sigma_zx[0], x)
ax5.plot(np.ones(np.size(x)) * use_material.sigma_t, x, '-.r')
ax5.plot(-np.ones(np.size(x)) * use_material.sigma_t, x, '-.r', label='line1')
ax5.set_title("Bending stress xz-plane")
ax5.set(xlabel=r'$\bar{\sigma}_z$ [Pa]', ylabel="x [m]")
ax5.grid(True)
ax5.axhline(0, color='black', lw=1.2)
ax6.plot(shear_x[0], x)
ax6.plot(np.ones(np.size(x)) * use_material.tau / 1.25, x, '-.r')
ax6.plot(-np.ones(np.size(x)) * use_material.tau / 1.25, x, '-.r')
ax6.set_title("Shear stress")
ax6.set(xlabel=r'$\bar{\tau}$ [Pa]')
ax6.grid(True)
ax6.axhline(0, color='black', lw=1.2)
fig3.savefig("Stress_diagrams_xz")

fig4, (ax7, ax8) = plt.subplots(1, 2, sharey=True)
ax7.plot(sigma_zy[0], x)
ax7.plot(np.ones(np.size(x)) * use_material.sigma_t, x, '-.r')
ax7.plot(-np.ones(np.size(x)) * use_material.sigma_t, x, '-.r', label='line1')
ax7.set_title("Bending stress yz-plane")
ax7.set(xlabel=r'$\bar{\sigma}_z$ [Pa]', ylabel="x [m]")
ax7.grid(True)
ax7.axhline(0, color='black', lw=1.2)
ax8.plot(shear_y[0], x)
ax8.plot(np.ones(np.size(x)) * use_material.tau / 1.25, x, '-.r')
ax8.plot(-np.ones(np.size(x)) * use_material.tau / 1.25, x, '-.r')
ax8.set_title("Shear stress")
ax8.set(xlabel=r'$\bar{\tau}$ [Pa]')
ax8.grid(True)
ax8.axhline(0, color='black', lw=1.2)
fig4.savefig("Stress_diagrams_yz")
plt.show()